### ISSUE TITLE
Add ReadME

### ISSUE THREAD

**Issue by euler16** [euler16/WeatherApp#3]
The Repository will be used for further reference , for students at CB. create a ReadME having the following info:
1. Purpose
2. functions/concepts used
3. A Note stating that the DarkSky API has been reset (so u need a new one to run)

**Comment by themakshter** [comment]
Can work on this in the evening today

**Comment by euler16** [comment]
@themakshter sure!! and thanks. Feel free to ask anything related

**Comment by euler16** [comment]
@themakshter your PR was amazing, I was surprised to know that u even added the screenshot of the app, something I wasn't expecting!!

**Comment by themakshter** [comment]
Haha I am glad it was useful!
